#
# Normal Rules : For creating/updating files
#
#
# Pattern Rules ...
#

PCC_OBJ_DIR=pcc_obj

pcc_obj/work_1.miau: work_1.wuff
	@echo Creating folder $(PCC_OBJ_DIR) if it does not exist yet
	@mkdir -p $(PCC_OBJ_DIR)
	@echo Pirate copying:
	@echo "   $(<) --> $(@)"
	@cp $(<) $(@)    































pcc_obj/work_2.miau: work_2.wuff
	@echo Creating folder $(PCC_OBJ_DIR) if it does not exist yet
	@mkdir -p $(PCC_OBJ_DIR)
	@echo Pirate copying:
	@echo "   $(<) --> $(@)"
	@cp $(<) $(@)    






























pcc_obj/work_3.miau: work_3.wuff
	@echo Creating folder $(PCC_OBJ_DIR) if it does not exist yet
	@mkdir -p $(PCC_OBJ_DIR)
	@echo Pirate copying:
	@echo "   $(<) --> $(@)"
	@cp $(<) $(@)    






























#pcc_obj/%.miau: %.wuff
#	@echo Creating folder $(PCC_OBJ_DIR) if it does not exist yet
#	@mkdir -p $(PCC_OBJ_DIR)
#	@echo Pirate copying:
#	@echo "   $(<) --> $(@)"
#	@cp $(<) $(@)    
